### ISSUE TITLE
Class and file organization

### ISSUE THREAD

**Issue by bstordrup** [JuanCrg90/Clean-Code-Notes#2]
There are a lot of information about keeping functions short, not too many parameters for functions and keeping classes small and dedicated specific purpose.

But what about the file-wise organization of classes? What is considered clean code in that aspect? Is it having one class per file? Or is it allowed to have multiple classes in the same file if they are in the same area. And what about languages that can split the interface definition into a different file than the implementation (like C++ with .h and .cpp files)?

**Comment by sumitanwar** [comment]
Thanks for that

**Comment by Vy89xxxx** [comment]
thank you

**Comment by JuanCrg90** [comment]
In my experience, keeping only one class per file is the best. This helps to have responsibility separation and allows new developers to get familiar with the codebase quickly. About the languages that allow a headers file and a source file, the best is also to keep only one class per group.
